routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\WebhookController;
use App\Http\Controllers\SendController;
use App\Http\Controllers\BotController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect(route('home'));
});

Route::post('webhooks', [WebhookController::class, 'index'])->name('webhooks.index');
Route::post('send/message', [SendController::class, 'message'])->name('send.message');
Route::post('send/location', [SendController::class, 'location'])->name('send.location');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('bots', BotController::class);
Route::post('bots/check', [BotController::class, 'check'])->name('bots.check');
Route::get('bots/{bot}/subscribers', [BotController::class, 'subscribers'])->name('bots.subscribers');
Route::delete('bots/{bot}/subscribers/{record}', [BotController::class, 'subscriberDestroy'])->name('bots.subscribers.destroy');

app/Models/Bot.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Bot extends Model
{
    use HasFactory;

    public function users()
    {
        return $this->hasMany(BotUser::class, 'trans_id');
    }

    public function owner()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Http/Controllers/BotController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Libraries\Telegram;
use Illuminate\Http\Request;

use App\Http\Requests\StoreBotRequest;
use App\Http\Requests\UpdateBotRequest;
use App\Models\Bot;
use App\Models\BotUser;

class BotController extends Controller
{
    protected $user;

    public function __construct()
    {
        $this->middleware('auth');

        $this->middleware(function ($request, $next) {
            $this->user = Auth::user();
            return $next($request);
        });

    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $records = Bot::where('user_id', $this->user->id)
            ->orderBy('id', 'desc')
            ->get();

        return view('bots.index', [
            'records' => $records
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('bots.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreBotRequest $request)
    {
        $record = new Bot;
        $record->bot_token = $request->bot_token;
        $record->bot_id = $request->bot_id;
        $record->bot_name = $request->bot_name;
        $record->bot_username = $request->bot_username;
        $record->user_id = $this->user->id;
        $record->save();

        $record = Bot::find($record->id);

        $webhookURL = env("WEBHOOK_URL");
        Telegram::setWebhook($record->bot_token, $webhookURL, true, $record->uid);
        Telegram::setMyCommands($record->bot_token, [
            [
                "command" => "/start",
                "description" => "Subscribe to the bot"
            ],
            [
                "command" => "/threadid",
                "description" => "Get the thread ID"
            ],
        ]);

        return redirect(route('bots.index'))->with('status', 'New Bot has been added.');
    }

    /**
     * Display the specified resource.
     */
    public function show(Bot $bot)
    {
        if ($this->user->id != $bot->user_id) {
            abort(404);
        }

        return view('bots.show', [
            'record' => $bot
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Bot $bot)
    {
        if ($this->user->id != $bot->user_id) {
            abort(404);
        }

        return view('bots.edit', [
            'record' => $bot
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateBotRequest $request, Bot $bot)
    {
        if ($this->user->id != $bot->user_id) {
            abort(401);
        }

        $bot->bot_token = $request->bot_token;
        $bot->bot_id = $request->bot_id;
        $bot->bot_name = $request->bot_name;
        $bot->bot_username = $request->bot_username;
        $bot->save();

        return redirect(route('bots.index'))->with('status', 'Bot has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Bot $bot)
    {
        if ($this->user->id != $bot->user_id) {
            abort(401);
        }

        $bot->delete();

        return redirect(route('bots.index'))->with('status', 'Bot has been deleted.');
    }

    public function check(Request $request)
    {
        $token = $request->input('token', '');

        $response = Telegram::getMe($token);
        $response = $response->json();

        if ($response['ok']) {
            return response()->json([
                'message' => 'Ok',
                'data' => $response['result']
            ], 200);
        }

        return response()->json([
            'message' => 'Not Found',
            'data' => null
        ], 404);
    }

    public function subscribers(Bot $bot)
    {
        if ($this->user->id != $bot->user_id) {
            abort(404);
        }

        $subscribers = $bot->users()->orderBy('id', 'desc')->get();

        return view('bots.subscribers', [
            'bot' => $bot,
            'records' => $subscribers
        ]);
    }

    public function subscriberDestroy(Bot $bot, BotUser $record)
    {
        if ($this->user->id != $bot->user_id) {
            abort(401);
        }

        $record->delete();

        return redirect(route('bots.subscribers', $bot->id))->with('status', 'Subscriber has been deleted.');
    }
}

resources/views/bots/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <form action="{{ route('bots.store') }}" method="post">
                        @csrf
                        <div class="card-header d-flex justify-content-between align-items-center">
                            <div class="fw-bold fs-5">
                                {{ __('Add Bot') }}
                            </div>
                        </div>

                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12 mb-2">
                                    <label for="bot_token">Token</label>
                                    <input type="text" name="bot_token" id="bot_token"
                                        class="form-control @error('bot_token') is-invalid @enderror"
                                        value="{{ old('bot_token') }}" placeholder="Bot Token" required>
                                    @error('bot_token')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <div class="col-md-4 mb-2">
                                    <label for="bot_id">ID</label>
                                    <input type="text" name="bot_id" id="bot_id"
                                        class="form-control @error('bot_id') is-invalid @enderror"
                                        value="{{ old('bot_id') }}" placeholder="Bot ID" readonly required>
                                    @error('bot_id')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <div class="col-md-4 mb-2">
                                    <label for="bot_name">Name</label>
                                    <input type="text" name="bot_name" id="bot_name"
                                        class="form-control @error('bot_name') is-invalid @enderror"
                                        value="{{ old('bot_name') }}" placeholder="Bot Name" readonly required>
                                    @error('bot_name')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <div class="col-md-4 mb-2">
                                    <label for="bot_username">Username</label>
                                    <input type="text" name="bot_username" id="bot_username"
                                        class="form-control @error('bot_username') is-invalid @enderror"
                                        value="{{ old('bot_username') }}" placeholder="Bot Username" readonly required>
                                    @error('bot_username')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>
                        </div>

                        <div class="card-footer d-flex justify-content-between align-items-center">
                            <a href="{{ route('bots.index') }}" class="btn btn-secondary"><i class="fa fa-chevron-left"></i>
                                Back</a>
                            <button id="submit" type="submit" class="btn btn-success" disabled><i
                                    class="fa fa-save"></i> Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        $(function() {
            let timer = 0;
            $('#bot_token').on('input', function() {
                $('#submit').prop('disabled', true);
                $(this).removeClass('is-valid');
                $(this).removeClass('is-invalid');
                $('#bot_id').val('');
                $('#bot_name').val('');
                $('#bot_username').val('');

                clearTimeout(timer);
                timer = setTimeout(() => {
                    axios.post('{{ route('bots.check') }}', {
                        token: $(this).val()
                    }).then(function(response) {
                        if (response.data.data) {
                            $('#submit').prop('disabled', false);
                            $('#bot_token').addClass('is-valid');

                            $('#bot_id').val(response.data.data.id);
                            $('#bot_name').val(response.data.data.first_name);
                            $('#bot_username').val(response.data.data.username);
                        } else {
                            $('#submit').prop('disabled', true);
                            $('#bot_token').addClass('is-invalid');
                        }
                    }).catch(function(error) {
                        $('#submit').prop('disabled', true);
                        $('#bot_token').addClass('is-invalid');
                    });
                }, 500);
            });
        });
    </script>
@endsection

resources/views/bots/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <form action="{{ route('bots.update', $record->id) }}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="card-header d-flex justify-content-between align-items-center">
                            <div class="fw-bold fs-5">
                                {{ __('Edit Bot') }}
                            </div>
                        </div>

                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12 mb-2">
                                    <label for="bot_token">Token</label>
                                    <input type="text" name="bot_token" id="bot_token"
                                        class="form-control @error('bot_token') is-invalid @enderror"
                                        value="{{ old('bot_token', $record->bot_token) }}" placeholder="Bot Token" required>
                                    @error('bot_token')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <div class="col-md-4 mb-2">
                                    <label for="bot_id">ID</label>
                                    <input type="text" name="bot_id" id="bot_id"
                                        class="form-control @error('bot_id') is-invalid @enderror"
                                        value="{{ old('bot_id', $record->bot_id) }}" placeholder="Bot ID" readonly required>
                                    @error('bot_id')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <div class="col-md-4 mb-2">
                                    <label for="bot_name">Name</label>
                                    <input type="text" name="bot_name" id="bot_name"
                                        class="form-control @error('bot_name') is-invalid @enderror"
                                        value="{{ old('bot_name', $record->bot_name) }}" placeholder="Bot Name" readonly required>
                                    @error('bot_name')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <div class="col-md-4 mb-2">
                                    <label for="bot_username">Username</label>
                                    <input type="text" name="bot_username" id="bot_username"
                                        class="form-control @error('bot_username') is-invalid @enderror"
                                        value="{{ old('bot_username', $record->bot_username) }}" placeholder="Bot Username" readonly required>
                                    @error('bot_username')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>
                        </div>

                        <div class="card-footer d-flex justify-content-between align-items-center">
                            <a href="{{ route('bots.index') }}" class="btn btn-secondary"><i class="fa fa-chevron-left"></i>
                                Back</a>
                            <button id="submit" type="submit" class="btn btn-success"><i
                                    class="fa fa-save"></i> Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        $(function() {
            let timer = 0;
            $('#bot_token').on('input', function() {
                $('#submit').prop('disabled', true);
                $(this).removeClass('is-valid');
                $(this).removeClass('is-invalid');
                $('#bot_id').val('');
                $('#bot_name').val('');
                $('#bot_username').val('');

                clearTimeout(timer);
                timer = setTimeout(() => {
                    axios.post('{{ route('bots.check') }}', {
                        token: $(this).val()
                    }).then(function(response) {
                        if (response.data.data) {
                            $('#submit').prop('disabled', false);
                            $('#bot_token').addClass('is-valid');

                            $('#bot_id').val(response.data.data.id);
                            $('#bot_name').val(response.data.data.first_name);
                            $('#bot_username').val(response.data.data.username);
                        } else {
                            $('#submit').prop('disabled', true);
                            $('#bot_token').addClass('is-invalid');
                        }
                    }).catch(function(error) {
                        $('#submit').prop('disabled', true);
                        $('#bot_token').addClass('is-invalid');
                    });
                }, 500);
            });
        });
    </script>
@endsection

resources/views/bots/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card rounded-0 rounded-top">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <div class="fw-bold fs-5">
                            {{ __('Bots') }}
                        </div>
                        <a href="{{ route('bots.create') }}" class="btn btn-success"><i class="fa fa-plus"></i> Add Bot</a>
                    </div>

                    <div class="card-body p-0">
                        @if (session('status'))
                            <div class="alert alert-success rounded-0 m-0" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <table class="table table-striped table-hover m-0">
                            <thead class="table-dark">
                                <tr>
                                    <th class="text-center" style="width: 5rem;">No.</th>
                                    <th>UID</th>
                                    <th>Bot ID</th>
                                    <th>Bot Name</th>
                                    <th>Bot Username</th>
                                    <th>Subscriber(s)</th>
                                    <th class="text-center" style="width: 15rem;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php
                                    $i = 1;
                                @endphp
                                @forelse ($records as $record)
                                    <tr>
                                        <td class="text-center">{{ $i }}</td>
                                        <td>{{ $record->uid }}</td>
                                        <td>{{ $record->bot_id }}</td>
                                        <td>{{ $record->bot_name }}</td>
                                        <td>{{ $record->bot_username }}</td>
                                        <td><a href="{{ route('bots.subscribers', $record->id) }}">{{ $record->users->count()  }}</a></td>
                                        <td class="text-center">
                                            <a href="{{ route('bots.show', $record->id) }}" class="btn btn-secondary btn-sm"><i class="fa fa-eye"></i></a>
                                            <a href="{{ route('bots.edit', $record->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
                                            <a
                                                href="{{ route('bots.destroy', $record->id) }}"
                                                class="btn btn-danger btn-sm"
                                                onclick="event.preventDefault();document.getElementById('delete-{{$record->id}}').submit();"
                                            >
                                                <i class="fa fa-trash"></i>
                                            </a>
                                            <form
                                                id="delete-{{$record->id}}"
                                                action="{{ route('bots.destroy', $record->id) }}"
                                                method="post"
                                                class="d-none"
                                            >
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        </td>
                                    </tr>
                                    @php
                                        $i++;
                                    @endphp
                                @empty
                                    <tr>
                                        <td colspan="99" class="text-center text-muted fst-italic">No Data.</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/bots/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <div class="fw-bold fs-5">
                            {{ __('Show Device') }}
                        </div>
                    </div>

                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12 mb-2">
                                <label for="bot_token">Token</label>
                                <input type="text" name="bot_token" id="bot_token" class="form-control" value="{{ $record->bot_token }}" placeholder="Bot Token" readonly>
                            </div>
                            <div class="col-md-4 mb-2">
                                <label for="bot_id">ID</label>
                                <input type="text" name="bot_id" id="bot_id" class="form-control" value="{{ $record->bot_id }}" placeholder="Bot ID" readonly>
                            </div>
                            <div class="col-md-4 mb-2">
                                <label for="bot_name">Name</label>
                                <input type="text" name="bot_name" id="bot_name" class="form-control" value="{{ $record->bot_name }}" placeholder="Bot Name" readonly>
                            </div>
                            <div class="col-md-4 mb-2">
                                <label for="bot_username">Username</label>
                                <input type="text" name="bot_username" id="bot_username" class="form-control" value="{{ $record->bot_username }}" placeholder="Bot Username" readonly>
                            </div>
                            <div class="col-md-12 mb-2">
                                <label for="uid">UID</label>
                                <input type="text" name="uid" id="uid" class="form-control" value="{{ $record->uid }}" placeholder="UID" readonly>
                            </div>
                        </div>
                    </div>

                    <div class="card-footer d-flex justify-content-between align-items-center">
                        <a href="{{ route('bots.index') }}" class="btn btn-secondary"><i class="fa fa-chevron-left"></i> Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/bots/subscribers.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card rounded-0 rounded-top">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <div class="fw-bold fs-5">
                            {{ $bot->bot_name }}'s Subscribers
                        </div>
                    </div>

                    <div class="card-body p-0">
                        @if (session('status'))
                            <div class="alert alert-success rounded-0 m-0" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <table class="table table-striped table-hover m-0">
                            <thead class="table-dark">
                                <tr>
                                    <th class="text-center" style="width: 5rem;">No.</th>
                                    <th>UID</th>
                                    <th>Chat ID</th>
                                    <th>Username</th>
                                    <th class="text-center" style="width: 15rem;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php
                                    $i = 1;
                                @endphp
                                @forelse ($records as $record)
                                    <tr>
                                        <td class="text-center">{{ $i }}</td>
                                        <td>{{ $record->uid }}</td>
                                        <td>{{ $record->chat_id }}</td>
                                        <td>{{ $record->username }}</td>
                                        <td class="text-center">
                                            <a
                                                href="{{ route('bots.subscribers.destroy', [$bot->id, $record->id]) }}"
                                                class="btn btn-danger btn-sm"
                                                onclick="event.preventDefault();document.getElementById('delete-{{$record->id}}').submit();"
                                            >
                                                <i class="fa fa-trash"></i>
                                            </a>
                                            <form
                                                id="delete-{{$record->id}}"
                                                action="{{ route('bots.subscribers.destroy', [$bot->id, $record->id]) }}"
                                                method="post"
                                                class="d-none"
                                            >
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        </td>
                                    </tr>
                                    @php
                                        $i++;
                                    @endphp
                                @empty
                                    <tr>
                                        <td colspan="99" class="text-center text-muted fst-italic">No Data.</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection